//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//


package com.tim9.accommodationserviceclient.dtos;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Extra_field")

public class ExtraFieldDTO {

    @XmlElement(name = "Extra_field_id")
    protected Long extraFieldId;
    
    
    @XmlElement(name = "Extra_field_name", required = true)
    protected String extraFieldName;
    
    
    @XmlElement(name = "Extra_price")
    protected float extraPrice;
    
    
    @XmlElement(name = "Optional")
    protected boolean optional;

    
    public Long getExtraFieldId() {
        return extraFieldId;
    }

    public void setExtraFieldId(Long value) {
        this.extraFieldId = value;
    }

 
    public String getExtraFieldName() {
        return extraFieldName;
    }

 
    public void setExtraFieldName(String value) {
        this.extraFieldName = value;
    }

  
    public float getExtraPrice() {
        return extraPrice;
    }

  
    public void setExtraPrice(float value) {
        this.extraPrice = value;
    }

 
    public boolean isOptional() {
        return optional;
    }

  
    public void setOptional(boolean value) {
        this.optional = value;
    }

}
