//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//


package com.tim9.accommodationserviceclient.dtos;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Picture")

public class PictureDTO {

    @XmlElement(name = "Picture_id")
    protected Long pictureId;
    
    
    @XmlElement(name = "Pic_url", required = true)
    protected String picUrl;

  
    public Long getPictureId() {
        return pictureId;
    }

 
    public void setPictureId(Long value) {
        this.pictureId = value;
    }

 
    public String getPicUrl() {
        return picUrl;
    }

 
    public void setPicUrl(String value) {
        this.picUrl = value;
    }

}
