//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//

package com.tim9.userservice.models;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.tim9.userservice.config.LocalDateTimeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "message")
@XmlRootElement(name = "Message")
@Entity
public class Message {

    @XmlElement(name = "messageId", required = true)
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    @Column
    protected Long messageId;
    
    @XmlElement(name = "messageBody", required = true)
    @Column
    protected String messageBody;
    
    @XmlElement(name = "messageTime", required = true)
    @XmlJavaTypeAdapter(value = LocalDateTimeAdapter.class)
    @Column
    protected LocalDateTime messageTime;
     
    @XmlElement(name = "userId", required = true)
    @Column
    protected Long userId;
    
    @XmlElement(name = "recieved", required = true)
    @Column
    protected boolean recieved;
    
    @XmlElement(name = "opened", required = true)
    @Column
    protected boolean opened;
    
    @XmlElement(name = "reservationId")
    @Column
    protected Long reservationId;
    
    @XmlElement(name = "lastUpdated")
    @XmlJavaTypeAdapter(value = LocalDateTimeAdapter.class)
    @Column
    protected LocalDateTime lastUpdated;

	public Long getMessageId() {
		return messageId;
	}

	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

	public String getMessageBody() {
		return messageBody;
	}

	public void setMessageBody(String messageBody) {
		this.messageBody = messageBody;
	}

	public LocalDateTime getMessageTime() {
		return messageTime;
	}

	public void setMessageTime(LocalDateTime messageTime) {
		this.messageTime = messageTime;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public boolean isRecieved() {
		return recieved;
	}

	public void setRecieved(boolean recieved) {
		this.recieved = recieved;
	}

	public boolean isOpened() {
		return opened;
	}

	public void setOpened(boolean opened) {
		this.opened = opened;
	}

	public Long getReservationId() {
		return reservationId;
	}

	public void setReservationId(Long reservationId) {
		this.reservationId = reservationId;
	}

	public LocalDateTime getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(LocalDateTime lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

    
	
}
