//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//


package com.tim9.agentapp.accommodation.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lukacvetinovic.backend_tim_9 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lukacvetinovic.backend_tim_9
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccommodationUnitLocal }
     * 
     */
    public AccommodationUnitLocal createAccommodationUnit() {
        return new AccommodationUnitLocal();
    }

    /**
     * Create an instance of {@link CategoryLocal }
     * 
     */
    public CategoryLocal createCategory() {
        return new CategoryLocal();
    }

    /**
     * Create an instance of {@link TypeLocal }
     * 
     */
    public TypeLocal createType() {
        return new TypeLocal();
    }

    /**
     * Create an instance of {@link ExtraFieldLocal }
     * 
     */
    public ExtraFieldLocal createExtraField() {
        return new ExtraFieldLocal();
    }

    /**
     * Create an instance of {@link PriceLocal }
     * 
     */
    public PriceLocal createPrice() {
        return new PriceLocal();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link AccommodationLocal }
     * 
     */
    public AccommodationLocal createAccommodation() {
        return new AccommodationLocal();
    }

    /**
     * Create an instance of {@link Picture }
     * 
     */
    public Picture createPicture() {
        return new Picture();
    }

}
