//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//


package com.tim9.agentapp.accommodation.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "Picture")
@Entity
@Table( name= "pictures" )
public class Picture {

    @XmlElement(name = "Local_picture_id")
    @Id
	@GeneratedValue ( strategy = GenerationType.IDENTITY )
	@Column ( name = "localId" )
    protected Long localPictureId;
    
    
    @XmlElement(name = "Picture_id")
	@Column ( name = "id" )
    protected Long pictureId;
    
    
    @XmlElement(name = "Pic_url", required = true)
    @Lob
	@Column ( name = "pic_url" )
    protected String picUrl;
    
    
    @XmlElement(name="Accommodation", required = true)
    @ManyToOne ()
	@JoinColumn (name="accommodation",nullable = false)
    protected Accommodation accommodation;

  
    public Long getPictureId() {
        return pictureId;
    }

 
    public void setPictureId(Long value) {
        this.pictureId = value;
    }

 
    public String getPicUrl() {
        return picUrl;
    }

 
    public void setPicUrl(String value) {
        this.picUrl = value;
    }

	public Long getLocalPictureId() {
		return localPictureId;
	}

	public void setLocalPictureId(Long localPictureId) {
		this.localPictureId = localPictureId;
	}


	public Accommodation getAccommodation() {
		return accommodation;
	}


	public void setAccommodation(Accommodation accommodation) {
		this.accommodation = accommodation;
	}

}
