//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 06:21:49 PM CEST 
//


package com.tim9.agentapp.accommodation.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Accommodation_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Number_of_days_before_cancelation" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element ref="{http://tim9.com}City"/&gt;
 *         &lt;element name="Counted_number_of_beds" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AgentId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Accommodation_units" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Accommodation_unit_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="Number_of_people" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element ref="{http://tim9.com}Category"/&gt;
 *                   &lt;element ref="{http://tim9.com}Type"/&gt;
 *                   &lt;element ref="{http://tim9.com}Accommodation"/&gt;
 *                   &lt;element ref="{http://tim9.com}Extra_field" maxOccurs="unbounded"/&gt;
 *                   &lt;element ref="{http://tim9.com}Price" maxOccurs="unbounded"/&gt;
 *                   &lt;element name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Accommodation_comments" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Comment_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="Comment_body" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Is_approved" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element ref="{http://tim9.com}Accommodation"/&gt;
 *                   &lt;element name="Client" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Accommodation_pictures" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Picture_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="Pic_url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element ref="{http://tim9.com}Accommodation"/&gt;
 *                   &lt;element name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accommodationId",
    "name",
    "description",
    "numberOfDaysBeforeCancelation",
    "city",
    "countedNumberOfBeds",
    "agentId",
    "accommodationUnits",
    "accommodationComments",
    "accommodationPictures",
    "lastUpdated"
})
@XmlRootElement(name = "Accommodation")
public class Accommodation {

    @XmlElement(name = "Accommodation_id")
    protected Long accommodationId;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Number_of_days_before_cancelation")
    protected int numberOfDaysBeforeCancelation;
    @XmlElement(name = "City", required = true)
    protected City city;
    @XmlElement(name = "Counted_number_of_beds")
    protected int countedNumberOfBeds;
    @XmlElement(name = "AgentId")
    protected long agentId;
    @XmlElement(name = "Accommodation_units")
    protected List<Accommodation.AccommodationUnits> accommodationUnits;
    @XmlElement(name = "Accommodation_comments")
    protected List<Accommodation.AccommodationComments> accommodationComments;
    @XmlElement(name = "Accommodation_pictures")
    protected List<Accommodation.AccommodationPictures> accommodationPictures;
    @XmlElement(name = "LastUpdated")
    protected String lastUpdated;

    /**
     * Gets the value of the accommodationId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccommodationId() {
        return accommodationId;
    }

    /**
     * Sets the value of the accommodationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccommodationId(Long value) {
        this.accommodationId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the numberOfDaysBeforeCancelation property.
     * 
     */
    public int getNumberOfDaysBeforeCancelation() {
        return numberOfDaysBeforeCancelation;
    }

    /**
     * Sets the value of the numberOfDaysBeforeCancelation property.
     * 
     */
    public void setNumberOfDaysBeforeCancelation(int value) {
        this.numberOfDaysBeforeCancelation = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link City }
     *     
     */
    public City getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link City }
     *     
     */
    public void setCity(City value) {
        this.city = value;
    }

    /**
     * Gets the value of the countedNumberOfBeds property.
     * 
     */
    public int getCountedNumberOfBeds() {
        return countedNumberOfBeds;
    }

    /**
     * Sets the value of the countedNumberOfBeds property.
     * 
     */
    public void setCountedNumberOfBeds(int value) {
        this.countedNumberOfBeds = value;
    }

    /**
     * Gets the value of the agentId property.
     * 
     */
    public long getAgentId() {
        return agentId;
    }

    /**
     * Sets the value of the agentId property.
     * 
     */
    public void setAgentId(long value) {
        this.agentId = value;
    }

    /**
     * Gets the value of the accommodationUnits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accommodationUnits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccommodationUnits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accommodation.AccommodationUnits }
     * 
     * 
     */
    public List<Accommodation.AccommodationUnits> getAccommodationUnits() {
        if (accommodationUnits == null) {
            accommodationUnits = new ArrayList<Accommodation.AccommodationUnits>();
        }
        return this.accommodationUnits;
    }

    /**
     * Gets the value of the accommodationComments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accommodationComments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccommodationComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accommodation.AccommodationComments }
     * 
     * 
     */
    public List<Accommodation.AccommodationComments> getAccommodationComments() {
        if (accommodationComments == null) {
            accommodationComments = new ArrayList<Accommodation.AccommodationComments>();
        }
        return this.accommodationComments;
    }

    /**
     * Gets the value of the accommodationPictures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accommodationPictures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccommodationPictures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accommodation.AccommodationPictures }
     * 
     * 
     */
    public List<Accommodation.AccommodationPictures> getAccommodationPictures() {
        if (accommodationPictures == null) {
            accommodationPictures = new ArrayList<Accommodation.AccommodationPictures>();
        }
        return this.accommodationPictures;
    }

    /**
     * Gets the value of the lastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the value of the lastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdated(String value) {
        this.lastUpdated = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Comment_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="Comment_body" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Is_approved" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element ref="{http://tim9.com}Accommodation"/&gt;
     *         &lt;element name="Client" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "commentId",
        "commentBody",
        "isApproved",
        "accommodation",
        "client",
        "lastUpdated"
    })
    public static class AccommodationComments {

        @XmlElement(name = "Comment_id")
        protected Long commentId;
        @XmlElement(name = "Comment_body", required = true)
        protected String commentBody;
        @XmlElement(name = "Is_approved")
        protected boolean isApproved;
        @XmlElement(name = "Accommodation", required = true)
        protected Accommodation accommodation;
        @XmlElement(name = "Client")
        protected long client;
        @XmlElement(name = "LastUpdated")
        protected String lastUpdated;

        /**
         * Gets the value of the commentId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getCommentId() {
            return commentId;
        }

        /**
         * Sets the value of the commentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setCommentId(Long value) {
            this.commentId = value;
        }

        /**
         * Gets the value of the commentBody property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommentBody() {
            return commentBody;
        }

        /**
         * Sets the value of the commentBody property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommentBody(String value) {
            this.commentBody = value;
        }

        /**
         * Gets the value of the isApproved property.
         * 
         */
        public boolean isIsApproved() {
            return isApproved;
        }

        /**
         * Sets the value of the isApproved property.
         * 
         */
        public void setIsApproved(boolean value) {
            this.isApproved = value;
        }

        /**
         * Gets the value of the accommodation property.
         * 
         * @return
         *     possible object is
         *     {@link Accommodation }
         *     
         */
        public Accommodation getAccommodation() {
            return accommodation;
        }

        /**
         * Sets the value of the accommodation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accommodation }
         *     
         */
        public void setAccommodation(Accommodation value) {
            this.accommodation = value;
        }

        /**
         * Gets the value of the client property.
         * 
         */
        public long getClient() {
            return client;
        }

        /**
         * Sets the value of the client property.
         * 
         */
        public void setClient(long value) {
            this.client = value;
        }

        /**
         * Gets the value of the lastUpdated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdated() {
            return lastUpdated;
        }

        /**
         * Sets the value of the lastUpdated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdated(String value) {
            this.lastUpdated = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Picture_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="Pic_url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element ref="{http://tim9.com}Accommodation"/&gt;
     *         &lt;element name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pictureId",
        "picUrl",
        "accommodation",
        "lastUpdated"
    })
    public static class AccommodationPictures {

        @XmlElement(name = "Picture_id")
        protected Long pictureId;
        @XmlElement(name = "Pic_url", required = true)
        protected String picUrl;
        @XmlElement(name = "Accommodation", required = true)
        protected Accommodation accommodation;
        @XmlElement(name = "LastUpdated")
        protected String lastUpdated;

        /**
         * Gets the value of the pictureId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getPictureId() {
            return pictureId;
        }

        /**
         * Sets the value of the pictureId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setPictureId(Long value) {
            this.pictureId = value;
        }

        /**
         * Gets the value of the picUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPicUrl() {
            return picUrl;
        }

        /**
         * Sets the value of the picUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPicUrl(String value) {
            this.picUrl = value;
        }

        /**
         * Gets the value of the accommodation property.
         * 
         * @return
         *     possible object is
         *     {@link Accommodation }
         *     
         */
        public Accommodation getAccommodation() {
            return accommodation;
        }

        /**
         * Sets the value of the accommodation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accommodation }
         *     
         */
        public void setAccommodation(Accommodation value) {
            this.accommodation = value;
        }

        /**
         * Gets the value of the lastUpdated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdated() {
            return lastUpdated;
        }

        /**
         * Sets the value of the lastUpdated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdated(String value) {
            this.lastUpdated = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Accommodation_unit_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="Number_of_people" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element ref="{http://tim9.com}Category"/&gt;
     *         &lt;element ref="{http://tim9.com}Type"/&gt;
     *         &lt;element ref="{http://tim9.com}Accommodation"/&gt;
     *         &lt;element ref="{http://tim9.com}Extra_field" maxOccurs="unbounded"/&gt;
     *         &lt;element ref="{http://tim9.com}Price" maxOccurs="unbounded"/&gt;
     *         &lt;element name="LastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accommodationUnitId",
        "numberOfPeople",
        "category",
        "type",
        "accommodation",
        "extraField",
        "price",
        "lastUpdated"
    })
    public static class AccommodationUnits {

        @XmlElement(name = "Accommodation_unit_id")
        protected Long accommodationUnitId;
        @XmlElement(name = "Number_of_people")
        protected int numberOfPeople;
        @XmlElement(name = "Category", required = true)
        protected Category category;
        @XmlElement(name = "Type", required = true)
        protected Type type;
        @XmlElement(name = "Accommodation", required = true)
        protected Accommodation accommodation;
        @XmlElement(name = "Extra_field", required = true)
        protected List<ExtraField> extraField;
        @XmlElement(name = "Price", required = true)
        protected List<Price> price;
        @XmlElement(name = "LastUpdated")
        protected String lastUpdated;

        /**
         * Gets the value of the accommodationUnitId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getAccommodationUnitId() {
            return accommodationUnitId;
        }

        /**
         * Sets the value of the accommodationUnitId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setAccommodationUnitId(Long value) {
            this.accommodationUnitId = value;
        }

        /**
         * Gets the value of the numberOfPeople property.
         * 
         */
        public int getNumberOfPeople() {
            return numberOfPeople;
        }

        /**
         * Sets the value of the numberOfPeople property.
         * 
         */
        public void setNumberOfPeople(int value) {
            this.numberOfPeople = value;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link Category }
         *     
         */
        public Category getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link Category }
         *     
         */
        public void setCategory(Category value) {
            this.category = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link Type }
         *     
         */
        public Type getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link Type }
         *     
         */
        public void setType(Type value) {
            this.type = value;
        }

        /**
         * Gets the value of the accommodation property.
         * 
         * @return
         *     possible object is
         *     {@link Accommodation }
         *     
         */
        public Accommodation getAccommodation() {
            return accommodation;
        }

        /**
         * Sets the value of the accommodation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accommodation }
         *     
         */
        public void setAccommodation(Accommodation value) {
            this.accommodation = value;
        }

        /**
         * Gets the value of the extraField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extraField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtraField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtraField }
         * 
         * 
         */
        public List<ExtraField> getExtraField() {
            if (extraField == null) {
                extraField = new ArrayList<ExtraField>();
            }
            return this.extraField;
        }

        /**
         * Gets the value of the price property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the price property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrice().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Price }
         * 
         * 
         */
        public List<Price> getPrice() {
            if (price == null) {
                price = new ArrayList<Price>();
            }
            return this.price;
        }

        /**
         * Gets the value of the lastUpdated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdated() {
            return lastUpdated;
        }

        /**
         * Sets the value of the lastUpdated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdated(String value) {
            this.lastUpdated = value;
        }

    }

}
