//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.18 at 11:05:49 AM CEST 
//


package com.tim9.agentapp.accommodation.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tim9.agentapp.accommodation.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Accommodation_QNAME = new QName("http://tim9.com/accommodationService", "Accommodation");
    private final static QName _AccommodationUnit_QNAME = new QName("http://tim9.com/accommodationService", "Accommodation_unit");
    private final static QName _Category_QNAME = new QName("http://tim9.com/accommodationService", "Category");
    private final static QName _City_QNAME = new QName("http://tim9.com/accommodationService", "City");
    private final static QName _Comment_QNAME = new QName("http://tim9.com/accommodationService", "Comment");
    private final static QName _ExtraField_QNAME = new QName("http://tim9.com/accommodationService", "Extra_field");
    private final static QName _Picture_QNAME = new QName("http://tim9.com/accommodationService", "Picture");
    private final static QName _Price_QNAME = new QName("http://tim9.com/accommodationService", "Price");
    private final static QName _Type_QNAME = new QName("http://tim9.com/accommodationService", "Type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tim9.agentapp.accommodation.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link ExtraField }
     * 
     */
    public ExtraField createExtraField() {
        return new ExtraField();
    }

    /**
     * Create an instance of {@link Picture }
     * 
     */
    public Picture createPicture() {
        return new Picture();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link AddExtraFieldToUnitRequest }
     * 
     */
    public AddExtraFieldToUnitRequest createAddExtraFieldToUnitRequest() {
        return new AddExtraFieldToUnitRequest();
    }

    /**
     * Create an instance of {@link AddExtraFieldToUnitResponse }
     * 
     */
    public AddExtraFieldToUnitResponse createAddExtraFieldToUnitResponse() {
        return new AddExtraFieldToUnitResponse();
    }

    /**
     * Create an instance of {@link CreateAccommodationRequest }
     * 
     */
    public CreateAccommodationRequest createCreateAccommodationRequest() {
        return new CreateAccommodationRequest();
    }

    /**
     * Create an instance of {@link CreateAccommodationResponse }
     * 
     */
    public CreateAccommodationResponse createCreateAccommodationResponse() {
        return new CreateAccommodationResponse();
    }

    /**
     * Create an instance of {@link CreateAccommodationUnitRequest }
     * 
     */
    public CreateAccommodationUnitRequest createCreateAccommodationUnitRequest() {
        return new CreateAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link CreateAccommodationUnitResponse }
     * 
     */
    public CreateAccommodationUnitResponse createCreateAccommodationUnitResponse() {
        return new CreateAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link CreatePictureRequest }
     * 
     */
    public CreatePictureRequest createCreatePictureRequest() {
        return new CreatePictureRequest();
    }

    /**
     * Create an instance of {@link CreatePictureResponse }
     * 
     */
    public CreatePictureResponse createCreatePictureResponse() {
        return new CreatePictureResponse();
    }

    /**
     * Create an instance of {@link CreatePriceRequest }
     * 
     */
    public CreatePriceRequest createCreatePriceRequest() {
        return new CreatePriceRequest();
    }

    /**
     * Create an instance of {@link CreatePriceResponse }
     * 
     */
    public CreatePriceResponse createCreatePriceResponse() {
        return new CreatePriceResponse();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitRequest }
     * 
     */
    public DeleteAccommodationUnitRequest createDeleteAccommodationUnitRequest() {
        return new DeleteAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitResponse }
     * 
     */
    public DeleteAccommodationUnitResponse createDeleteAccommodationUnitResponse() {
        return new DeleteAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link DeletePictureRequest }
     * 
     */
    public DeletePictureRequest createDeletePictureRequest() {
        return new DeletePictureRequest();
    }

    /**
     * Create an instance of {@link DeletePictureResponse }
     * 
     */
    public DeletePictureResponse createDeletePictureResponse() {
        return new DeletePictureResponse();
    }

    /**
     * Create an instance of {@link DeletePriceRequest }
     * 
     */
    public DeletePriceRequest createDeletePriceRequest() {
        return new DeletePriceRequest();
    }

    /**
     * Create an instance of {@link DeletePriceResponse }
     * 
     */
    public DeletePriceResponse createDeletePriceResponse() {
        return new DeletePriceResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationRequest }
     * 
     */
    public GetAccommodationRequest createGetAccommodationRequest() {
        return new GetAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitsRequest }
     * 
     */
    public GetAccommodationUnitsRequest createGetAccommodationUnitsRequest() {
        return new GetAccommodationUnitsRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitsResponse }
     * 
     */
    public GetAccommodationUnitsResponse createGetAccommodationUnitsResponse() {
        return new GetAccommodationUnitsResponse();
    }

    /**
     * Create an instance of {@link GetCategoriesRequest }
     * 
     */
    public GetCategoriesRequest createGetCategoriesRequest() {
        return new GetCategoriesRequest();
    }

    /**
     * Create an instance of {@link GetCategoriesResponse }
     * 
     */
    public GetCategoriesResponse createGetCategoriesResponse() {
        return new GetCategoriesResponse();
    }

    /**
     * Create an instance of {@link GetCitiesRequest }
     * 
     */
    public GetCitiesRequest createGetCitiesRequest() {
        return new GetCitiesRequest();
    }

    /**
     * Create an instance of {@link GetCitiesResponse }
     * 
     */
    public GetCitiesResponse createGetCitiesResponse() {
        return new GetCitiesResponse();
    }

    /**
     * Create an instance of {@link GetCommentsRequest }
     * 
     */
    public GetCommentsRequest createGetCommentsRequest() {
        return new GetCommentsRequest();
    }

    /**
     * Create an instance of {@link GetCommentsResponse }
     * 
     */
    public GetCommentsResponse createGetCommentsResponse() {
        return new GetCommentsResponse();
    }

    /**
     * Create an instance of {@link GetExtraFieldsRequest }
     * 
     */
    public GetExtraFieldsRequest createGetExtraFieldsRequest() {
        return new GetExtraFieldsRequest();
    }

    /**
     * Create an instance of {@link GetExtraFieldsResponse }
     * 
     */
    public GetExtraFieldsResponse createGetExtraFieldsResponse() {
        return new GetExtraFieldsResponse();
    }

    /**
     * Create an instance of {@link GetPicturesRequest }
     * 
     */
    public GetPicturesRequest createGetPicturesRequest() {
        return new GetPicturesRequest();
    }

    /**
     * Create an instance of {@link GetPicturesResponse }
     * 
     */
    public GetPicturesResponse createGetPicturesResponse() {
        return new GetPicturesResponse();
    }

    /**
     * Create an instance of {@link GetPricesRequest }
     * 
     */
    public GetPricesRequest createGetPricesRequest() {
        return new GetPricesRequest();
    }

    /**
     * Create an instance of {@link GetPricesResponse }
     * 
     */
    public GetPricesResponse createGetPricesResponse() {
        return new GetPricesResponse();
    }

    /**
     * Create an instance of {@link GetTypesRequest }
     * 
     */
    public GetTypesRequest createGetTypesRequest() {
        return new GetTypesRequest();
    }

    /**
     * Create an instance of {@link GetTypesResponse }
     * 
     */
    public GetTypesResponse createGetTypesResponse() {
        return new GetTypesResponse();
    }

    /**
     * Create an instance of {@link RemoveExtraFieldFromUnitRequest }
     * 
     */
    public RemoveExtraFieldFromUnitRequest createRemoveExtraFieldFromUnitRequest() {
        return new RemoveExtraFieldFromUnitRequest();
    }

    /**
     * Create an instance of {@link RemoveExtraFieldFromUnitResponse }
     * 
     */
    public RemoveExtraFieldFromUnitResponse createRemoveExtraFieldFromUnitResponse() {
        return new RemoveExtraFieldFromUnitResponse();
    }

    /**
     * Create an instance of {@link UpdateAccommodationRequest }
     * 
     */
    public UpdateAccommodationRequest createUpdateAccommodationRequest() {
        return new UpdateAccommodationRequest();
    }

    /**
     * Create an instance of {@link UpdateAccommodationResponse }
     * 
     */
    public UpdateAccommodationResponse createUpdateAccommodationResponse() {
        return new UpdateAccommodationResponse();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitRequest }
     * 
     */
    public UpdateAccommodationUnitRequest createUpdateAccommodationUnitRequest() {
        return new UpdateAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitResponse }
     * 
     */
    public UpdateAccommodationUnitResponse createUpdateAccommodationUnitResponse() {
        return new UpdateAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Accommodation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Accommodation }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Accommodation")
    public JAXBElement<Accommodation> createAccommodation(Accommodation value) {
        return new JAXBElement<Accommodation>(_Accommodation_QNAME, Accommodation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccommodationUnit }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccommodationUnit }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Accommodation_unit")
    public JAXBElement<AccommodationUnit> createAccommodationUnit(AccommodationUnit value) {
        return new JAXBElement<AccommodationUnit>(_AccommodationUnit_QNAME, AccommodationUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Category }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Category }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Category")
    public JAXBElement<Category> createCategory(Category value) {
        return new JAXBElement<Category>(_Category_QNAME, Category.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link City }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link City }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "City")
    public JAXBElement<City> createCity(City value) {
        return new JAXBElement<City>(_City_QNAME, City.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Comment }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Comment }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Comment")
    public JAXBElement<Comment> createComment(Comment value) {
        return new JAXBElement<Comment>(_Comment_QNAME, Comment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtraField }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtraField }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Extra_field")
    public JAXBElement<ExtraField> createExtraField(ExtraField value) {
        return new JAXBElement<ExtraField>(_ExtraField_QNAME, ExtraField.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Picture }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Picture }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Picture")
    public JAXBElement<Picture> createPicture(Picture value) {
        return new JAXBElement<Picture>(_Picture_QNAME, Picture.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Price }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Price }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Price")
    public JAXBElement<Price> createPrice(Price value) {
        return new JAXBElement<Price>(_Price_QNAME, Price.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Type }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Type }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com/accommodationService", name = "Type")
    public JAXBElement<Type> createType(Type value) {
        return new JAXBElement<Type>(_Type_QNAME, Type.class, null, value);
    }

}
