//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 06:21:49 PM CEST 
//


package com.tim9.agentapp.accommodation.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tim9.agentapp.accommodation.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccommodationUnit_QNAME = new QName("http://tim9.com", "Accommodation_unit");
    private final static QName _Comment_QNAME = new QName("http://tim9.com", "Comment");
    private final static QName _Picture_QNAME = new QName("http://tim9.com", "Picture");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tim9.agentapp.accommodation.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Accommodation.AccommodationUnits }
     * 
     */
    public Accommodation.AccommodationUnits createAccommodationAccommodationUnits() {
        return new Accommodation.AccommodationUnits();
    }

    /**
     * Create an instance of {@link Accommodation.AccommodationComments }
     * 
     */
    public Accommodation.AccommodationComments createAccommodationAccommodationComments() {
        return new Accommodation.AccommodationComments();
    }

    /**
     * Create an instance of {@link Accommodation.AccommodationPictures }
     * 
     */
    public Accommodation.AccommodationPictures createAccommodationAccommodationPictures() {
        return new Accommodation.AccommodationPictures();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link ExtraField }
     * 
     */
    public ExtraField createExtraField() {
        return new ExtraField();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link CreateAccommodationRequest }
     * 
     */
    public CreateAccommodationRequest createCreateAccommodationRequest() {
        return new CreateAccommodationRequest();
    }

    /**
     * Create an instance of {@link CreateAccommodationResponse }
     * 
     */
    public CreateAccommodationResponse createCreateAccommodationResponse() {
        return new CreateAccommodationResponse();
    }

    /**
     * Create an instance of {@link CreateAccommodationUnitRequest }
     * 
     */
    public CreateAccommodationUnitRequest createCreateAccommodationUnitRequest() {
        return new CreateAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link CreateAccommodationUnitResponse }
     * 
     */
    public CreateAccommodationUnitResponse createCreateAccommodationUnitResponse() {
        return new CreateAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link CreatePictureRequest }
     * 
     */
    public CreatePictureRequest createCreatePictureRequest() {
        return new CreatePictureRequest();
    }

    /**
     * Create an instance of {@link CreatePictureResponse }
     * 
     */
    public CreatePictureResponse createCreatePictureResponse() {
        return new CreatePictureResponse();
    }

    /**
     * Create an instance of {@link CreatePriceRequest }
     * 
     */
    public CreatePriceRequest createCreatePriceRequest() {
        return new CreatePriceRequest();
    }

    /**
     * Create an instance of {@link CreatePriceResponse }
     * 
     */
    public CreatePriceResponse createCreatePriceResponse() {
        return new CreatePriceResponse();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitRequest }
     * 
     */
    public DeleteAccommodationUnitRequest createDeleteAccommodationUnitRequest() {
        return new DeleteAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link DeleteAccommodationUnitResponse }
     * 
     */
    public DeleteAccommodationUnitResponse createDeleteAccommodationUnitResponse() {
        return new DeleteAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link DeletePictureRequest }
     * 
     */
    public DeletePictureRequest createDeletePictureRequest() {
        return new DeletePictureRequest();
    }

    /**
     * Create an instance of {@link DeletePictureResponse }
     * 
     */
    public DeletePictureResponse createDeletePictureResponse() {
        return new DeletePictureResponse();
    }

    /**
     * Create an instance of {@link DeletePriceRequest }
     * 
     */
    public DeletePriceRequest createDeletePriceRequest() {
        return new DeletePriceRequest();
    }

    /**
     * Create an instance of {@link DeletePriceResponse }
     * 
     */
    public DeletePriceResponse createDeletePriceResponse() {
        return new DeletePriceResponse();
    }

    /**
     * Create an instance of {@link EditAccommodationRequest }
     * 
     */
    public EditAccommodationRequest createEditAccommodationRequest() {
        return new EditAccommodationRequest();
    }

    /**
     * Create an instance of {@link EditAccommodationResponse }
     * 
     */
    public EditAccommodationResponse createEditAccommodationResponse() {
        return new EditAccommodationResponse();
    }

    /**
     * Create an instance of {@link EditAccommodationUnitRequest }
     * 
     */
    public EditAccommodationUnitRequest createEditAccommodationUnitRequest() {
        return new EditAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link EditAccommodationUnitResponse }
     * 
     */
    public EditAccommodationUnitResponse createEditAccommodationUnitResponse() {
        return new EditAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationRequest }
     * 
     */
    public GetAccommodationRequest createGetAccommodationRequest() {
        return new GetAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitsRequest }
     * 
     */
    public GetAccommodationUnitsRequest createGetAccommodationUnitsRequest() {
        return new GetAccommodationUnitsRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitsResponse }
     * 
     */
    public GetAccommodationUnitsResponse createGetAccommodationUnitsResponse() {
        return new GetAccommodationUnitsResponse();
    }

    /**
     * Create an instance of {@link GetCategoriesRequest }
     * 
     */
    public GetCategoriesRequest createGetCategoriesRequest() {
        return new GetCategoriesRequest();
    }

    /**
     * Create an instance of {@link GetCategoriesResponse }
     * 
     */
    public GetCategoriesResponse createGetCategoriesResponse() {
        return new GetCategoriesResponse();
    }

    /**
     * Create an instance of {@link GetCitiesRequest }
     * 
     */
    public GetCitiesRequest createGetCitiesRequest() {
        return new GetCitiesRequest();
    }

    /**
     * Create an instance of {@link GetCitiesResponse }
     * 
     */
    public GetCitiesResponse createGetCitiesResponse() {
        return new GetCitiesResponse();
    }

    /**
     * Create an instance of {@link GetCommentsRequest }
     * 
     */
    public GetCommentsRequest createGetCommentsRequest() {
        return new GetCommentsRequest();
    }

    /**
     * Create an instance of {@link GetCommentsResponse }
     * 
     */
    public GetCommentsResponse createGetCommentsResponse() {
        return new GetCommentsResponse();
    }

    /**
     * Create an instance of {@link GetExtraFieldsRequest }
     * 
     */
    public GetExtraFieldsRequest createGetExtraFieldsRequest() {
        return new GetExtraFieldsRequest();
    }

    /**
     * Create an instance of {@link GetExtraFieldsResponse }
     * 
     */
    public GetExtraFieldsResponse createGetExtraFieldsResponse() {
        return new GetExtraFieldsResponse();
    }

    /**
     * Create an instance of {@link GetPictureRequest }
     * 
     */
    public GetPictureRequest createGetPictureRequest() {
        return new GetPictureRequest();
    }

    /**
     * Create an instance of {@link GetPictureResponse }
     * 
     */
    public GetPictureResponse createGetPictureResponse() {
        return new GetPictureResponse();
    }

    /**
     * Create an instance of {@link GetPriceRequests }
     * 
     */
    public GetPriceRequests createGetPriceRequests() {
        return new GetPriceRequests();
    }

    /**
     * Create an instance of {@link GetPriceResponse }
     * 
     */
    public GetPriceResponse createGetPriceResponse() {
        return new GetPriceResponse();
    }

    /**
     * Create an instance of {@link GetTypeRequest }
     * 
     */
    public GetTypeRequest createGetTypeRequest() {
        return new GetTypeRequest();
    }

    /**
     * Create an instance of {@link GetTypeResponse }
     * 
     */
    public GetTypeResponse createGetTypeResponse() {
        return new GetTypeResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com", name = "Accommodation_unit")
    public JAXBElement<Object> createAccommodationUnit(Object value) {
        return new JAXBElement<Object>(_AccommodationUnit_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com", name = "Comment")
    public JAXBElement<Object> createComment(Object value) {
        return new JAXBElement<Object>(_Comment_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com", name = "Picture")
    public JAXBElement<Object> createPicture(Object value) {
        return new JAXBElement<Object>(_Picture_QNAME, Object.class, null, value);
    }

}
