//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.18 at 09:29:42 AM CEST 
//


package com.tim9.agentapp.user.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tim9.agentapp.user.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Admin_QNAME = new QName("http://tim9.com", "Admin");
    private final static QName _Agent_QNAME = new QName("http://tim9.com", "Agent");
    private final static QName _Message_QNAME = new QName("http://tim9.com", "Message");
    private final static QName _User_QNAME = new QName("http://tim9.com", "User");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tim9.agentapp.user.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Admin }
     * 
     */
    public Admin createAdmin() {
        return new Admin();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link CreateMessageRequest }
     * 
     */
    public CreateMessageRequest createCreateMessageRequest() {
        return new CreateMessageRequest();
    }

    /**
     * Create an instance of {@link CreateMessageResponse }
     * 
     */
    public CreateMessageResponse createCreateMessageResponse() {
        return new CreateMessageResponse();
    }

    /**
     * Create an instance of {@link GetAgentRequest }
     * 
     */
    public GetAgentRequest createGetAgentRequest() {
        return new GetAgentRequest();
    }

    /**
     * Create an instance of {@link GetAgentResponse }
     * 
     */
    public GetAgentResponse createGetAgentResponse() {
        return new GetAgentResponse();
    }

    /**
     * Create an instance of {@link GetMessagesRequest }
     * 
     */
    public GetMessagesRequest createGetMessagesRequest() {
        return new GetMessagesRequest();
    }

    /**
     * Create an instance of {@link GetMessagesResponse }
     * 
     */
    public GetMessagesResponse createGetMessagesResponse() {
        return new GetMessagesResponse();
    }

    /**
     * Create an instance of {@link UpdateAgentPasswordRequest }
     * 
     */
    public UpdateAgentPasswordRequest createUpdateAgentPasswordRequest() {
        return new UpdateAgentPasswordRequest();
    }

    /**
     * Create an instance of {@link UpdateAgentPasswordResponse }
     * 
     */
    public UpdateAgentPasswordResponse createUpdateAgentPasswordResponse() {
        return new UpdateAgentPasswordResponse();
    }

    /**
     * Create an instance of {@link UpdateAgentRequest }
     * 
     */
    public UpdateAgentRequest createUpdateAgentRequest() {
        return new UpdateAgentRequest();
    }

    /**
     * Create an instance of {@link UpdateAgentResponse }
     * 
     */
    public UpdateAgentResponse createUpdateAgentResponse() {
        return new UpdateAgentResponse();
    }

    /**
     * Create an instance of {@link UpdateMessageRequest }
     * 
     */
    public UpdateMessageRequest createUpdateMessageRequest() {
        return new UpdateMessageRequest();
    }

    /**
     * Create an instance of {@link UpdateMessageResponse }
     * 
     */
    public UpdateMessageResponse createUpdateMessageResponse() {
        return new UpdateMessageResponse();
    }

    /**
     * Create an instance of {@link AbstractUser }
     * 
     */
    public AbstractUser createAbstractUser() {
        return new AbstractUser();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Admin }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Admin }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com", name = "Admin")
    public JAXBElement<Admin> createAdmin(Admin value) {
        return new JAXBElement<Admin>(_Admin_QNAME, Admin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Agent }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Agent }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com", name = "Agent")
    public JAXBElement<Agent> createAgent(Agent value) {
        return new JAXBElement<Agent>(_Agent_QNAME, Agent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Message }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com", name = "Message")
    public JAXBElement<Message> createMessage(Message value) {
        return new JAXBElement<Message>(_Message_QNAME, Message.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link User }{@code >}
     */
    @XmlElementDecl(namespace = "http://tim9.com", name = "User")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

}
