//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.04 at 02:39:52 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tim9.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tim9.agentapp.user.wsdl;
