//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.18 at 11:10:30 AM CEST 
//


package com.tim9.agentapp.reservation.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reservation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reservation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Reservation_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="Date_from" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Date_to" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Final_price" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="Confirmation" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Accommodation_unit" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Client" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservation", propOrder = {
    "reservationId",
    "dateFrom",
    "dateTo",
    "finalPrice",
    "confirmation",
    "accommodationUnit",
    "client"
})
public class Reservation {

    @XmlElement(name = "Reservation_id")
    protected Long reservationId;
    @XmlElement(name = "Date_from", required = true)
    protected String dateFrom;
    @XmlElement(name = "Date_to", required = true)
    protected String dateTo;
    @XmlElement(name = "Final_price")
    protected float finalPrice;
    @XmlElement(name = "Confirmation")
    protected boolean confirmation;
    @XmlElement(name = "Accommodation_unit")
    protected long accommodationUnit;
    @XmlElement(name = "Client")
    protected long client;

    /**
     * Gets the value of the reservationId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReservationId() {
        return reservationId;
    }

    /**
     * Sets the value of the reservationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReservationId(Long value) {
        this.reservationId = value;
    }

    /**
     * Gets the value of the dateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFrom() {
        return dateFrom;
    }

    /**
     * Sets the value of the dateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFrom(String value) {
        this.dateFrom = value;
    }

    /**
     * Gets the value of the dateTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTo() {
        return dateTo;
    }

    /**
     * Sets the value of the dateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTo(String value) {
        this.dateTo = value;
    }

    /**
     * Gets the value of the finalPrice property.
     * 
     */
    public float getFinalPrice() {
        return finalPrice;
    }

    /**
     * Sets the value of the finalPrice property.
     * 
     */
    public void setFinalPrice(float value) {
        this.finalPrice = value;
    }

    /**
     * Gets the value of the confirmation property.
     * 
     */
    public boolean isConfirmation() {
        return confirmation;
    }

    /**
     * Sets the value of the confirmation property.
     * 
     */
    public void setConfirmation(boolean value) {
        this.confirmation = value;
    }

    /**
     * Gets the value of the accommodationUnit property.
     * 
     */
    public long getAccommodationUnit() {
        return accommodationUnit;
    }

    /**
     * Sets the value of the accommodationUnit property.
     * 
     */
    public void setAccommodationUnit(long value) {
        this.accommodationUnit = value;
    }

    /**
     * Gets the value of the client property.
     * 
     */
    public long getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     */
    public void setClient(long value) {
        this.client = value;
    }

}
