//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//


package com.tim9.agentapp.accommodation.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "Accommodation_unit")

public class AccommodationUnitDTO {

    @XmlElement(name = "Accommodation_unit_id")
    protected Long accommodationUnitId;
    
    
    @XmlElement(name = "Number_of_people")
    protected int numberOfPeople;
    
    
    @XmlElement(name = "Category", required = true)
    protected CategoryDTO category;
    
    
    @XmlElement(name = "Type", required = true)
    protected TypeDTO type;
    
    
    @XmlElement(name = "Extra_field", required = true)
    protected List<ExtraFieldDTO> extraField = new ArrayList<ExtraFieldDTO>();
    
    
    @XmlElement(name = "Price", required = true)
    protected List<PriceDTO> price =  new ArrayList<PriceDTO>();


    public Long getAccommodationUnitId() {
        return accommodationUnitId;
    }


    public void setAccommodationUnitId(Long value) {
        this.accommodationUnitId = value;
    }


    public int getNumberOfPeople() {
        return numberOfPeople;
    }


    public void setNumberOfPeople(int value) {
        this.numberOfPeople = value;
    }


    public CategoryDTO getCategory() {
        return category;
    }


    public void setCategory(CategoryDTO value) {
        this.category = value;
    }


    public TypeDTO getType() {
        return type;
    }


    public void setType(TypeDTO value) {
        this.type = value;
    }


    public List<ExtraFieldDTO> getExtraField() {
        if (extraField == null) {
            extraField = new ArrayList<ExtraFieldDTO>();
        }
        return this.extraField;
    }

 
    public List<PriceDTO> getPrice() {
        if (price == null) {
            price = new ArrayList<PriceDTO>();
        }
        return this.price;
    }

}
