//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//


package com.tim9.agentapp.accommodation.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "Type")
public class TypeDTO {

    @XmlElement(name = "Type_id")
    protected Long typeId;
    
    
    @XmlElement(name = "Type_name", required = true)
    protected String typeName;

  
    public Long getTypeId() {
        return typeId;
    }

 
    public void setTypeId(Long value) {
        this.typeId = value;
    }

  
    public String getTypeName() {
        return typeName;
    }

  
    public void setTypeName(String value) {
        this.typeName = value;
    }

}
