//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:50:21 AM CEST 
//


package com.tim9.accommodationservice.dtos;


import java.time.LocalDate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Price")
public class PriceDTO {

    @XmlElement(name = "Price_id")
    protected Long priceId;
    
    
    @XmlElement(name = "Date_from", required = true)
    @XmlSchemaType(name = "date")
    protected LocalDate dateFrom;
    
    
    @XmlElement(name = "Amount")
    protected float amount;
    
    @XmlElement(name = "Date_to", required = true)
    @XmlSchemaType(name = "date")
    protected LocalDate dateTo;

  
    public Long getPriceId() {
        return priceId;
    }

 
    public void setPriceId(Long value) {
        this.priceId = value;
    }

 
    public LocalDate getDateFrom() {
        return dateFrom;
    }

 
    public void setDateFrom(LocalDate value) {
        this.dateFrom = value;
    }

  
    public float getAmount() {
        return amount;
    }

  
    public void setAmount(float value) {
        this.amount = value;
    }

  
    public LocalDate getDateTo() {
        return dateTo;
    }

  
    public void setDateTo(LocalDate value) {
        this.dateTo = value;
    }

}
